### ISSUE TITLE
Objetivos do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArteNaMao#10]
Seus principais objetivos de negócios são:

1. (**INCORRETO**) oferecer uma solução abrangente e aumentar a eficiência operacional, promovendo o sucesso dos negócios de artesanato. 
2. Do ponto de vista do cliente, o objetivo é:
- simplificar a gestão de negócios, (O QUE É SIMPLIFICAR?)
- substituir métodos manuais por uma solução mais eficaz (RETIRE OS ADJETIVOS)
- (**INCORRETO**) personalizar o software para atender às necessidades individuais. 

Em resumo, o "Arte na Mão" visa simplificar e otimizar as operações de artesãos e pequenos empresários, impulsionando o sucesso tanto para os negócios quanto para os clientes. (MUITO GENÉRICO)

OS OBJETIVOS PRECISAM SER MAIS ESPECÍFICOS E VERIFICÁVEIS.
REFAÇAM.

**Comment by marsicanogeorge** [comment]
**Não resolvido:**

**Objetivos do Produto**
No contexto atual, empreendedores e artesãos do setor de artesanato enfrentam desafios significativos na gestão de seus negócios, incluindo estoque, vendas e organização administrativa complexa. O software "ArteNaMão" foi desenvolvido especificamente para atender a essas necessidades. Seus principais objetivos de negócios são facilitar a gestão administrativa e financeira do atêlie, promovendo o sucesso dos negócios de artesanato. 

Do ponto de vista do cliente, **o objetivo é diminuir a complexidade da gestão de negócios e substituir métodos manuais e complexos por uma solução simples.** 

**

> _Simplifiquem. Como vcs vão fazer para verificar se esse objetivo foi cumprido, ou não?_

**


Em resumo, o "Arte na Mão" visa otimizar as operações de artesãos por meio de listas e gráficos que interagem entre si para gerar um maior entendimento da gestão administrativa e financeira do empreendimento .

**Comment by marsicanogeorge** [comment]
Não resolvido:

Objetivos do Produto
No contexto atual, empreendedores e artesãos do setor de artesanato enfrentam desafios significativos na gestão de seus negócios, incluindo estoque, vendas e organização administrativa complexa. O software "ArteNaMão" foi desenvolvido especificamente para atender a essas necessidades. Seus principais objetivos de negócios são facilitar a gestão administrativa e financeira do atêlie, promovendo o sucesso dos negócios de artesanato.

Do ponto de vista do cliente, o objetivo é diminuir a complexidade da gestão de negócios e substituir métodos manuais e complexos por uma solução simples.

**

Simplifiquem. Como vcs vão fazer para verificar se esse objetivo foi cumprido, ou não?

**

Em resumo, o "Arte na Mão" visa otimizar as operações de artesãos por meio de listas e gráficos que interagem entre si para gerar um maior entendimento da gestão administrativa e financeira do empreendimento .

**Comment by The-Boss-Nina** [comment]
Foram realizadas as devidas melhorias sugeridas pelo professor.
