### ISSUE TITLE
USM

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ArteNaMao#23]
No geral, o mapa está bom.
Apenas algumas atividades, possuem tarefas em nível de granularidade muito baixo. Revejam, e se necessário agrupem a atividade com outra.

**Comment by marsicanogeorge** [comment]
![image](https://github.com/mdsreq-fga-unb/2023.2-ArteNaMao/assets/68402547/57050647-d98d-4bf7-8d3c-9da4fe3bafdc)

**Comment by pxarthur** [comment]
Agrupamos as três atividades com o menor nível de granularidade em uma só, que define os principais detalhes de um evento como: data, horário, local, tipo do evento etc.
